kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo sansar
  - echo ramro duniya chha hai

- name: es
  image: alpine
  commands:
  - echo hola

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

trigger:
  branch:
  - master
